### ISSUE TITLE
文字化け@しおり

### ISSUE THREAD

**Issue by taro3621** [wtsnjp/texlive-ja#1]
朝倉様

Acrobat Reader で見ますと，しおりが文字化けを起こしております．

追記希望としては，GPG設定方法と角藤先生TLW64インストールがございます．
2018と比し LuaTeX-ja が OpenTypeフォントGSUB(proportional)対応が完璧に
なった代わりにWindowsデフォインストール32ビット版ではメモリ不足で組版
不能になったもので．

よろしくご査収の程を．

**Comment by wtsnjp** [comment]
ご報告ありがとうございます．

しおりが文字化けしている件については先ほど修正しました (2eab1f411ba5b6ecb5d4caa32a853cb2e30ac88d)．プレビュー版 PDF への反映はもう少しお待ち下さい．

GPG 設定方法については日本語版だけで追記するのは奇妙なので，TeX Live 本家側に要望してみようと思います．将来的に本家 (texlive-en) で説明が追記されましたら日本語版も追随したいと思います．

TLW64 についても日本語版だけで対応することではなさそうなので本家に相談します．ただ（Windows を常用していないこともあり，あまりよくわかっていないのですが）これは W32TeX 内のもののようにも見え，その場合 TeX Live 側でドキュメント化する可能性は低い気もします（W32TeX のドキュメントに記載される方が自然かと）．

**Comment by aminophen** [comment]
> TLW64 についても日本語版だけで対応することではなさそうなので本家に相談します．ただ（Windows を常用していないこともあり，あまりよくわかっていないのですが）これは W32TeX 内のもののようにも見え，その場合 TeX Live 側でドキュメント化する可能性は低い気もします（W32TeX のドキュメントに記載される方が自然かと）．

現状 win64 support は非公式扱いと理解しています。一応角藤さんによると
https://tug.org/pipermail/tex-live/2019-March/043185.html
に書かれている instruction を読むことになっています。来年あたりに win64 が標準で install-tl でサポートされれば，本家 ドキュメント (texlive-en) でも言及されると思いますが，その場合は手動ではなくなるのでドキュメント化の意味は…。

**Comment by wtsnjp** [comment]
なるほど，TLW64 というのはそういう状況のものなのですね．現状の texlive-en.pdf には1.2節 (p.3) に

> There are no special 64-bit executables for Windows, but the 32-bit executables should run on 64-bit systems.

という記述があるので，64-bit が正式にサポートされれば本家が更新されるでしょう．日本語版としては，やはりそれに追随する形にしたいと思います．
