### ISSUE TITLE
訳が気になるところ（1～2節）

### ISSUE THREAD

**Issue by zr-tex8r** [wtsnjp/texlive-ja#2]
「原文と言ってることがかなり食い違う」と感じたところ。

* See section 2.1 for alternate solutions for Windows and Mac OS X.   
  （WindwosおよびMac OS X**に対する別の方策**については2.1節を参照されたい。）  
  WindowsおよびmacOS**に特有のその他の事情**については2.1節を参照してください．

  ※つまり、TeX Live以外にMacTeXやproTeXtをインストールするという方法がある、ということ。

* This section lists the predefined variables specifying the texmf trees used by the system, and their intended purpose, and the default layout of TeX Live. 
  （**この節では、** システムで使用するtexmfツリーを指定する定義済変数、およびそれらの所期の目的、および**TeX Liveでの既定の構成を列挙する**。）  
  **このセクションでは**システムに利用される種々のTEXMFツリーを指定するために予め定義されている変数を一覧にします．**これらのTEXMFツリーは**それぞれに使用目的があり，また**TeX Liveのデフォルト構成を示すものでもあります**．  

  ※原文は“This section list the default layout.”であって、自分はこれ自体に無理があると感じるけど、意図は恐らく「この節では既定の構成**を説明する**」なのだと思う。

* All of the trees, including the personal ones, should follow the TeX Directory Structure (…), with all its myriad subdirectories, or files may not be found.   
  （個人用のものを含め、全てのツリーは**その大量のサブディレクトリとともに**「TeXディレクトリ構成（…）」に従うべきであり、**さもないとファイルが見つからない可能性がある**。）
  すべてのTEXMFツリーは，たとえ個人的なものであっても，標準的なTeXのディレクトリ構成 (…) にしたがうべきです．**ただし必要のないサブディレクトリやファイルは存在していなくても構いません．**

  ※orは文接続詞。

**Comment by wtsnjp** [comment]
ありがとうございます．いずれもご指摘の通り誤訳だったと思われるため，上のコミットで修正しました．
