### ISSUE TITLE
訳が気になるところ（6節）

### ISSUE THREAD

**Issue by zr-tex8r** [wtsnjp/texlive-ja#3]
Windows屋なので6節を読んでみた。

* Under Windows, the installer does some extra things:  
（Windowsでは**インストーラは**いくつか追加の処理を行う：）  
Windowsでは**TeX Liveは**いくつか追加の処理を行います：

※やっぱり主語は「（TeX Live）インストーラ」であるべきだと思います。

* the PS_View (psv) PostScript previewer  
（PS_View（psv）PostScriptプレビューア）  
PostScriptビューア（psv）

※多分「PS_View」がソフトウェア名で「psv」がコマンド名なのでしょう。片方だけでもいいけど、この文で「psv」だけ出して後の文で「PS_View」だけ出したのでは同じソフトウェアを指していることが明確でないと思います。

* If enabled, TeXworks, Dviout and PS_view become either the default program for their respective filetypes, or get an entry in the ‘Open with’ right-click menus of those filetypes.  
（……。**あるいは**、それらのファイルタイプに対する右クリックメニューの「プログラムから開く」の中の項目として**これらのプログラム**が含められる。）  
……．**また**関連するファイルを右クリックして「プログラムから開く」を選択した場合に**TeX Liveのプログラム**が候補に上がるようになります．

※原文は“OR”で訳文は“AND”になってるけど、これは実際には“AND”の方が正しいのでしょうか？

※後半の文の主語も前半と同じだから、「TeX Liveのプログラム」では不必要に曖昧である気がします。（これも実際は違うのかな？）

* User Profile  
（ユーザ**プロファイル**）  
「ユーザ**プロフィール**」

※公式の訳語としては「ユーザー プロファイル」のようです。（実際にWindowsのUIでそう表記されている。）まあ、「ユーザー」と「ユーザ」みたいな表記ゆれの一種とも見なせますが。

* The most important ones for installation programs are `HKEY_CURRENT_USER` and `HKEY_LOCAL_MACHINE`, `HKCU` and `HKLM` in short.  
（インストールプログラムにとって最も重要なものは`HKEY_CURRENT_USER`と`HKEY_LOCAL_MACHINE`（**略称は**`HKCU`と`HKLM`）。）  
**簡単に言うと**，インストールプログラムにとって最も重要なものは`HKEY_CURRENT_USER`，`HKEY_LOCAL_MACHINE`，`HKCU`，`HKLM`です．

※つまり`HKEY_CURRENT_USER`を略したのが`HKCU`。4つ並列されているとすると最初の“and”が余計。

* if you try to allocate an array of 25,000,000 reals,   
（2500万要素の**実数**配列を確保しようとすると…）  
例えばasyで25,000,000**リール**の配列を確保しようとしたり，

※realはAsymptoteのデータ型の一つ。リールは“reel”。

**Comment by wtsnjp** [comment]
ありがとうございます．いずれも上記コミットで修正しました．

翻訳作業中に，私が原版の記述が明らかに誤りだと思って意図的に意味の異なる訳出をしたり翻訳を保留（コメントアウト）したりしている箇所はすべて [`feedback.txt`](https://github.com/wtsnjp/texlive-ja/blob/master/feedback.txt) で言及しているはずなので，それ以外の問題は意図せぬ誤訳の可能性が高いです．

ユーザプロフィール/ユーザプロファイルは表記ゆれを嫌った結果そうなっていたもので迷いましたが，公式に合わせた方が（Windows ユーザな）読者にわかりやすいだろうとの判断で「ユーザプロファイル」を採用することにしました．
