### ISSUE TITLE
訳が気になるところ（改訂部分）

### ISSUE THREAD

**Issue by zr-tex8r** [wtsnjp/texlive-ja#4]
2019年12月の版(91c4dec)から更新された箇所について。

### 5節

* (1) Figure 9 shows …  
（(1) 図9に**示されて**いるのは…）  
ひとつは図9で**表示されて**いるのは…

※この意味のshowを「表示する」とするのは自分はとても不自然に感じる。

※「ひとつは～は」もなんか落ち着かない。

### 7節

* Comments start with `%`, either at the beginning of a line or preceded by whitespace, and continue to the end of the line.  
（コメントは**行頭**あるいは空白の直後にある`%`で開始し、その行の末尾まで続きます。）  
`%`はコメント開始文字で，行末までコメントとして扱われます．`%`の前にいくつか空白文字があっても同様です．

※今の訳文だと「非空白文字の直後の`%`もコメント開始になる」と解釈される。

* Considered as strings, *value* may contain any character.  
（文字列と見なされる**ため**、*value*は任意の文字を含められる。）  
文字列とみなせる**限り**，`value`にはあらゆる文字を含めることができます．

※理由を表しているのだと思う。「文字列と見なされない」場合はなさそう。

* the path `~$USER/{foo,bar}//baz`,  
パス`$USER/{foo,bar}//baz`は

※`~`が抜けている。（この例の`$USER`はホームディレクトリ名ではなくユーザ名を表すはず。）

* at the beginning or the end of a path, or doubled in the middle, it substitutes the default path expansion.  
（パスの先頭や末尾**に書かれた場合**および途中で2つ続けて書かれた場合は、その部分はデフォルトパスの展開形**で置き換えられる**。）  
先頭や末尾，あるいは途中において連続して，置かれた場合はデフォルトパス展開されます．

※このコンマの使い方は苦しいし、結局「先頭や末尾あるいは途中において」と読まれる可能性がありそう。

※「デフォルトパス展開されます」では通じなさそう。

* The rules are inherent in the multiple levels of interpretation of the configuration (parsing, expansion, search, …) and so …  
設定の解釈の各段階の処理（パース、展開、検索…）に不可分に結びついているため、…  
それぞれのルールは，種々の処理（パース，展開，検索など）**のうちの**固有のタイミングで適用されるため，残念ながら簡潔に説明することはできません．

※「のうちの」は変。「に」でいいと思う

※全体として、内容がかなり違う気がする……。

### 9節

* as a system-dependent extension  
（システム依存の拡張として）  
この拡張はシステム**非**依存です．

※えっ！

※「システム依存」の意味は多分「TeX Live独自の」あるいは「Web2C独自の」なんだと思う。

**Comment by wtsnjp** [comment]
いつもありがとうございます．上記のすべての修正に加えて，Twitter で言及されていた「欧文フォントと和文フォントのどちらがより導入が難しいか」については，このドキュメントではそもそも触れる必要がない内容なので，両者を比較するような文言は削りました．

また事後報告の形になり恐縮ですが，2020年版から新たに加えることにした日本語版独自の「訳者まえがき」において謝辞掲載させていただいています．
