### ISSUE TITLE
脱字報告

### ISSUE THREAD

**Issue by tsuu32** [wtsnjp/texlive-ja#5]
一件だけですが、脱字と思われるものを見つけました。

https://github.com/wtsnjp/texlive-ja/blob/e95bbfe8c984ac64e2700798934719a31950957b/texlive-ja.tex#L544

「インストール」の脱字だと思います。

**Comment by wtsnjp** [comment]
ありがとうございます！ 直しました．

**Comment by tsuu32** [comment]
ありがとうございます！
